import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className="dark">
      <body
        className={`antialiased`}
      >
        <Navbar />
        <main className="mt-12 max-w-6xl mx-auto">
        {children}
        </main>
      </body>
    </html>
  );
}
